version: "3.8"
services: 
    api:
        container_name: wareclouds_playground_api
        image: node:12-alpine
        volumes:
            - type: bind
              source: ./
              target: /app
            - type: volume
              source: nodemodules 
              target: /app/node_modules
              volume:
                nocopy: true
        working_dir: /app
        command: npm run dev
        ports:
            - "5000:5000"
        environment: 
            - NODE_ENV=development
            - PORT=5000
            - MONGO_HOST=mongodb://db:27017/wareclouds_architecture
            - MONGO_USER=
            - MONGO_PASS=
    db:
        container_name: mongo_wareclouds_playground
        image: mongo
        ports:
            - "27017:27017"
        volumes: 
            - mongodata:/data/db
volumes:
    nodemodules:
    mongodata:
        
            
        
